export const SET_VENUE_LIST = "SET_VENUE_LIST";
export const SET_VENUE_DETAIL = "SET_VENUE_DETAIL";
export const SET_VENUE_COURT = "SET_VENUE_COURT";
export const SET_PROVINCES = "SET_PROVINCES";

export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_TOKEN_REQUEST_FORGOT = "SET_TOKEN_REQUEST_FORGOT";

export const SET_FACILITY_TYPE = "SET_FACILITY_TYPE";

export const SET_WAITING_PAYMENT = "SET_WAITING_PAYMENT";
export const SET_WAITING_PAYMENT_DETAIL = "SET_WAITING_PAYMENT_DETAIL";
export const SET_WAITING_APPROVAL = "SET_WAITING_APPROVAL";
export const SET_WAITING_APPROVAL_DETAIL = "SET_WAITING_APPROVAL_DETAIL";
export const SET_RESERVED = "SET_RESERVED";
export const SET_RESERVED_DETAIL = "SET_RESERVED_DETAIL";
export const SET_DONE = "SET_DONE";

export const SET_COURT_DETAIL = "SET_COURT_DETAIL";
export const SET_SCHEDULE_TIME = "SET_SCHEDULE_TIME";
export const SET_CART = "SET_CART";
export const SET_PAYMENT_BOOKING_HOUR = "SET_PAYMENT_BOOKING_HOUR";
export const SET_BANK_NAMES = "SET_BANK_NAMES";
