export const SET_VENUE_LIST = "SET_VENUE_LIST";
export const SET_VENUE_DETAIL = "SET_VENUE_DETAIL";

export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_TOKEN_REQUEST_FORGOT = "SET_TOKEN_REQUEST_FORGOT";

export const SET_FACILITY_TYPE = "SET_FACILITY_TYPE";
