export const SET_VENUE_LIST = "SET_VENUE_LIST";
export const SET_VENUE_DETAIL = "SET_VENUE_DETAIL";
export const SET_VENUE_COURT = "SET_VENUE_COURT";

export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_TOKEN_REQUEST_FORGOT = "SET_TOKEN_REQUEST_FORGOT";

export const SET_FACILITY_TYPE = "SET_FACILITY_TYPE";

export const SET_WAITING_PAYMENT = "SET_WAITING_PAYMENT";
export const SET_RESERVED = "SET_RESERVED";
export const SET_DONE = "SET_DONE";
